server:
  port: 8084
  wait-time-in-ms-when-sync-empty: 3000

spring:
  spring:
    profiles:
      active: native
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: venda
      auto-index-creation: true

application:
  produtoService:
    url: http://localhost:8083
    endpointConsultarProduto: ${application.produtoService.url}/produto
  clienteService:
    url: http://localhost:8082
    endpointConsultarCliente: ${application.clienteService.url}/cliente/isCadastrado/{id}
application-version: 2.0